travis:
  secure:
    BINSTAR_TOKEN: kVb2oUStHYR2JFvetX92xe7gVDMI6PuNOkE0vy+f9iq3TbLNDEowqdl18x47X+e8W+tloHMaTl8q0F+FVUqtw5FPvbulxapMAzUAMGkxXsKpKJRjJdQ5VH7AgmjiRSCCHduXM08akP3V41pe/l8AdKhloveiGouAkustLPqf+4IW57V4P3kHGz/TUkudtl+uSUPYlQXv0JE573wynN8Ur0EEdOq4OUHdwQviAyK0Fb9HaY9mCe1FIwFeKkevRiTfuaYGqwnW2SVEHGBhlIqQp4c5zivMtk8qb1xhaVW2EgAS9SKwEC9vVFmMxVE3WoeB1bVV0spnIIEgIEiDXJsYW0OXX/X1d5wlk7OaJMnCtHrkeHKG0ykQlRZvTNXzDs/EMe9Mz35zBtDiYpTyktUti3RDAbGJoI1GMsIRQMYf/hCX/t2+ntwTMPC9ym4QwKtfUQbXn5Ap4pSQm3nkn4vK0SgaNewf2vwxx0X+WNlteM6wL58nzvbCOoewS9xAUtaCPtqJo0vez7M0ax/OEiMYUbWVcZEViys00ooaRyV1eiPK/D6SyRmU2b88CkLr0oEO2Ol/l9OHZtupk6K6eOBfDd7xJotsK32NvowUOFMnY9RJdse20bs9StCQ5rnSIVqF4WVPPDKKQJXyJvPMsyLPBb0xx7E3esje/g+x0G3Drto=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
