travis:
  secure:
    BINSTAR_TOKEN: qzdloVd/d8tYXS7Wt3kpyfKhQKNb7ut4Ck8ZQLtyeLOwp1+/+irz/Ph1qrNC3op4vSuKuRUG+p8QNFWglwoVJ7ttTDfxTHwC0wlom/tlm7J31TTjv15X/tXlcZuOHhSXXiGx9ASrlu9P+J7+dkTZMKSo9+uh/VIg8t8vDjaB8vB2QjYbhAg2WGIeaMXUnuMOcaeChGTaVn8vR6EpGuYElAYSIoiZfWG5hGmyUmmJ52GpoqQ+ABIjERN/aKt7Ed5RE2Uh53nKeGGrNhZs5mfHoJZg6O4bs8rbYgOthsm7g+uU3T9LH44JVPKrXkjJaFmQ1SLyZ9aoG5H8x6cNjgSCMoFK6Pv0VWxXe4YZ5AoZzn7St/D9nIog9HKXVkkrnez+DNBjVPb0oU7r+CljgudWVUvaydsAhFliR4eZeVoGf6v3UBznsvMw1iieei1FKdsxVPZiR5qhBQK8GpDfnx4jXA4kuakv91PcM9BU1xAip+lT+97Ix9GnWx5QsPszWwaJYHxcy/8V3ONIQ1P1yxqqU4d63b8UZ1ejE7A6XjsPkniumu3i10cNTzgx06m0jrEayt5LKrExllMX/bYgQMtvDyA2ddmCaaU7zERMgRA/Ma34cqXD6yN+p6Zb94wM9QaB0eiNR3YazpKqjCMu6+cWrFK27TmDqdadlTl1Ht2AvUo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
