travis:
  secure:
    BINSTAR_TOKEN: QCA+oFahojflc71dYIRcQMhUX1UVtAHmI3yqLDrt/15zICmDMBur7ILEU6U9Rb25yonlkMF1FZno4zgzwpjkJDA3WdLrkI4yq5pvdg0GlH9D6I7T0yhpQNhhAlrN2DO+e9fzoSTfL1eZDH7XiaOgmI2U0zD6S4h0KF9Q6Yln0fStKELQLBalydlEgNA1FsSFM2B2yVddgrP+K/pwyzNeKzS7Y6utpul0HgtPuBZnySsNsgAqKgx7d4QOSvdn8E3kKbVcRRaUe2jIh3emwXxyFsJvOrQs1s3E6WZRXTlIDBBBGRDDw9trPou5TPHiV4a1gQq+vDS8vP1nRK6IW0EGnRyRuHEfyTcTZ1KSagM70j0jqEoyvHNxuppPrxZxhDGEUWL8XXLHTBqko+4t6E6Kbea0VxLU2qVHQapfzVEkKeJ5ROuV6dFCeFMPE2nCAsXNAbTioHPm3ILvhJ5b2U7HnbwEB1tWUnuVQAMjKsFP+nAryHvl6SfB48wQuroMJt4NmsifsGD0vlh1KtXhY1x9qh4jC14pldoipReYyi31v3Q6OqCYwwXibnwuVSevbsoeUm1TaLewpBHhb9Jq/jhfrKZypzZSFr1JDOBLrCRpV1Tby/PKJ3e0eIsJKtVJz1wO4LEi90MP/KQzOBSmyBKCRNgWdZO54lxZfNydR5rF4A0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
